<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="sample Suite" duration-ms="34545" started-at="2018-10-22T16:35:05Z" finished-at="2018-10-22T16:35:40Z">
    <groups>
      <group name="testHome">
        <method signature="LoginTest.validLogin()[pri:0, instance:Test.testCore.LoginTest@28feb3fa]" name="validLogin" class="Test.testCore.LoginTest"/>
      </group> <!-- testHome -->
    </groups>
    <test name="Test" duration-ms="34545" started-at="2018-10-22T16:35:05Z" finished-at="2018-10-22T16:35:40Z">
      <class name="Test.testCore.LoginTest">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:Test.testCore.LoginTest@28feb3fa]" name="setup" is-config="true" duration-ms="33651" started-at="2018-10-22T22:05:05Z" finished-at="2018-10-22T22:05:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="validLogin()[pri:0, instance:Test.testCore.LoginTest@28feb3fa]" name="validLogin" duration-ms="15" started-at="2018-10-22T22:05:39Z" finished-at="2018-10-22T22:05:39Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Test.testCore.LoginTest.validLogin(LoginTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
        <test-method status="PASS" signature="close()[pri:0, instance:Test.testCore.LoginTest@28feb3fa]" name="close" is-config="true" duration-ms="853" started-at="2018-10-22T22:05:39Z" finished-at="2018-10-22T22:05:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- Test.testCore.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- sample Suite -->
</testng-results>
